name: 'PR Code Coverage Report Action'
description: 'PR Code Coverage Report Action'
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'